-- Auto-generated from the original Prisma seed data. Safe to re-run:
-- products/inventory are upserted by unique sku, inventory balances are
-- only set on first insert so re-seeding never clobbers live scan data.

insert into products (brand, line, shade_code, sku, ideal_stock_level)
values
  ('Redken', 'Shades EQ', '09V', 'redken-shades-eq-09v', 8),
  ('L''Oréal Professionnel', 'Majirel', '6.3', 'l-or-al-professionnel-majirel-6-3', 8),
  ('Wella Professionals', 'Koleston Perfect', '7/43', 'wella-professionals-koleston-perfect-7-43', 8),
  ('Schwarzkopf', 'Igora Royal', '5-65', 'schwarzkopf-igora-royal-5-65', 8),
  ('Goldwell', 'Topchic', '6N', 'goldwell-topchic-6n', 8),
  ('Redken', 'Shades EQ', '7NA', 'redken-shades-eq-7na', 6),
  ('Wella Professionals', 'Illumina Color', '8/69', 'wella-professionals-illumina-color-8-69', 6),
  ('L''Oréal Professionnel', 'INOA', '7.1', 'l-or-al-professionnel-inoa-7-1', 8),
  ('Schwarzkopf', 'Igora Royal', '4-99', 'schwarzkopf-igora-royal-4-99', 6),
  ('Goldwell', 'Elumen', 'BL@all', 'goldwell-elumen-bl-all', 5)
on conflict (sku) do update set ideal_stock_level = excluded.ideal_stock_level;

insert into products (brand, line, shade_code, sku, ideal_stock_level)
values
  ('L''Oréal Professionnel', 'Majirel', '1', 'l-or-al-professionnel-majirel-1', 4),
  ('L''Oréal Professionnel', 'Majirel', '3', 'l-or-al-professionnel-majirel-3', 4),
  ('L''Oréal Professionnel', 'Majirel', '4', 'l-or-al-professionnel-majirel-4', 4),
  ('L''Oréal Professionnel', 'Majirel', '5', 'l-or-al-professionnel-majirel-5', 4),
  ('L''Oréal Professionnel', 'Majirel', '6', 'l-or-al-professionnel-majirel-6', 4),
  ('L''Oréal Professionnel', 'Majirel', '7', 'l-or-al-professionnel-majirel-7', 4),
  ('L''Oréal Professionnel', 'Majirel', '8', 'l-or-al-professionnel-majirel-8', 4),
  ('L''Oréal Professionnel', 'Majirel', '9', 'l-or-al-professionnel-majirel-9', 4),
  ('L''Oréal Professionnel', 'Majirel', '10', 'l-or-al-professionnel-majirel-10', 4),
  ('L''Oréal Professionnel', 'Majirel', '4.0', 'l-or-al-professionnel-majirel-4-0', 4),
  ('L''Oréal Professionnel', 'Majirel', '5.0', 'l-or-al-professionnel-majirel-5-0', 4),
  ('L''Oréal Professionnel', 'Majirel', '6.0', 'l-or-al-professionnel-majirel-6-0', 4),
  ('L''Oréal Professionnel', 'Majirel', '7.0', 'l-or-al-professionnel-majirel-7-0', 4),
  ('L''Oréal Professionnel', 'Majirel', '8.0', 'l-or-al-professionnel-majirel-8-0', 4),
  ('L''Oréal Professionnel', 'Majirel', '4.20', 'l-or-al-professionnel-majirel-4-20', 4),
  ('L''Oréal Professionnel', 'Majirel', '7.1', 'l-or-al-professionnel-majirel-7-1', 4),
  ('L''Oréal Professionnel', 'Majirel', '7.11', 'l-or-al-professionnel-majirel-7-11', 4),
  ('L''Oréal Professionnel', 'Majirel', '7.12', 'l-or-al-professionnel-majirel-7-12', 4),
  ('L''Oréal Professionnel', 'Majirel', '7.21', 'l-or-al-professionnel-majirel-7-21', 4),
  ('L''Oréal Professionnel', 'Majirel', '7.3', 'l-or-al-professionnel-majirel-7-3', 4),
  ('L''Oréal Professionnel', 'Majirel', '7.32', 'l-or-al-professionnel-majirel-7-32', 4),
  ('L''Oréal Professionnel', 'Majirel', '7.4', 'l-or-al-professionnel-majirel-7-4', 4),
  ('L''Oréal Professionnel', 'Majirel', '7.43', 'l-or-al-professionnel-majirel-7-43', 4),
  ('L''Oréal Professionnel', 'Majirel', '5.3', 'l-or-al-professionnel-majirel-5-3', 4),
  ('L''Oréal Professionnel', 'Majirel', '6.34', 'l-or-al-professionnel-majirel-6-34', 4),
  ('L''Oréal Professionnel', 'Majirel', '9.1', 'l-or-al-professionnel-majirel-9-1', 4),
  ('L''Oréal Professionnel', 'Majirel', '5.12', 'l-or-al-professionnel-majirel-5-12', 4),
  ('L''Oréal Professionnel', 'Majirel', '8.11', 'l-or-al-professionnel-majirel-8-11', 4),
  ('L''Oréal Professionnel', 'Majirel', '9.11', 'l-or-al-professionnel-majirel-9-11', 4),
  ('L''Oréal Professionnel', 'Majirel', '10.1', 'l-or-al-professionnel-majirel-10-1', 4),
  ('L''Oréal Professionnel', 'Majirel', '10.21', 'l-or-al-professionnel-majirel-10-21', 4),
  ('L''Oréal Professionnel', 'Majirel', '4.35', 'l-or-al-professionnel-majirel-4-35', 4),
  ('L''Oréal Professionnel', 'Majirel', '5.32', 'l-or-al-professionnel-majirel-5-32', 4),
  ('L''Oréal Professionnel', 'Majirel', '5.4', 'l-or-al-professionnel-majirel-5-4', 4),
  ('L''Oréal Professionnel', 'Majirel', '5.52', 'l-or-al-professionnel-majirel-5-52', 4),
  ('L''Oréal Professionnel', 'Majirel', '5.60', 'l-or-al-professionnel-majirel-5-60', 4),
  ('L''Oréal Professionnel', 'Majirel', '6.32', 'l-or-al-professionnel-majirel-6-32', 4),
  ('L''Oréal Professionnel', 'Majirel', '6.45', 'l-or-al-professionnel-majirel-6-45', 4),
  ('L''Oréal Professionnel', 'Majirel', '6.66', 'l-or-al-professionnel-majirel-6-66', 4),
  ('L''Oréal Professionnel', 'Majirel', '7.31', 'l-or-al-professionnel-majirel-7-31', 4),
  ('L''Oréal Professionnel', 'Majirel', '7.44', 'l-or-al-professionnel-majirel-7-44', 4),
  ('L''Oréal Professionnel', 'Majirel', '8.34', 'l-or-al-professionnel-majirel-8-34', 4),
  ('L''Oréal Professionnel', 'Majirel', '8.43', 'l-or-al-professionnel-majirel-8-43', 4),
  ('L''Oréal Professionnel', 'Majirel', '9.3', 'l-or-al-professionnel-majirel-9-3', 4),
  ('L''Oréal Professionnel', 'INOA', '4', 'l-or-al-professionnel-inoa-4', 4),
  ('L''Oréal Professionnel', 'INOA', '5.3', 'l-or-al-professionnel-inoa-5-3', 4),
  ('L''Oréal Professionnel', 'INOA', '7.11', 'l-or-al-professionnel-inoa-7-11', 4),
  ('L''Oréal Professionnel', 'INOA', '8.1', 'l-or-al-professionnel-inoa-8-1', 4),
  ('L''Oréal Professionnel', 'INOA', '9', 'l-or-al-professionnel-inoa-9', 4),
  ('L''Oréal Professionnel', 'INOA', '1', 'l-or-al-professionnel-inoa-1', 4),
  ('L''Oréal Professionnel', 'INOA', '3', 'l-or-al-professionnel-inoa-3', 4),
  ('L''Oréal Professionnel', 'INOA', '5', 'l-or-al-professionnel-inoa-5', 4),
  ('L''Oréal Professionnel', 'INOA', '6', 'l-or-al-professionnel-inoa-6', 4),
  ('L''Oréal Professionnel', 'INOA', '7', 'l-or-al-professionnel-inoa-7', 4),
  ('L''Oréal Professionnel', 'INOA', '8', 'l-or-al-professionnel-inoa-8', 4),
  ('L''Oréal Professionnel', 'INOA', '10', 'l-or-al-professionnel-inoa-10', 4),
  ('L''Oréal Professionnel', 'INOA', '4.3', 'l-or-al-professionnel-inoa-4-3', 4),
  ('L''Oréal Professionnel', 'INOA', '6.3', 'l-or-al-professionnel-inoa-6-3', 4),
  ('L''Oréal Professionnel', 'INOA', '7.3', 'l-or-al-professionnel-inoa-7-3', 4),
  ('L''Oréal Professionnel', 'INOA', '8.3', 'l-or-al-professionnel-inoa-8-3', 4),
  ('L''Oréal Professionnel', 'INOA', '9.3', 'l-or-al-professionnel-inoa-9-3', 4),
  ('L''Oréal Professionnel', 'INOA', '5.18', 'l-or-al-professionnel-inoa-5-18', 4),
  ('L''Oréal Professionnel', 'INOA', '7.18', 'l-or-al-professionnel-inoa-7-18', 4),
  ('L''Oréal Professionnel', 'INOA', '5.11', 'l-or-al-professionnel-inoa-5-11', 4),
  ('L''Oréal Professionnel', 'INOA', '9.11', 'l-or-al-professionnel-inoa-9-11', 4),
  ('L''Oréal Professionnel', 'INOA', '4.20', 'l-or-al-professionnel-inoa-4-20', 4),
  ('L''Oréal Professionnel', 'INOA', '5.25', 'l-or-al-professionnel-inoa-5-25', 4),
  ('L''Oréal Professionnel', 'INOA', '6.46', 'l-or-al-professionnel-inoa-6-46', 4),
  ('Wella Professionals', 'Koleston Perfect', '2/0', 'wella-professionals-koleston-perfect-2-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '3/0', 'wella-professionals-koleston-perfect-3-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '4/0', 'wella-professionals-koleston-perfect-4-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '5/0', 'wella-professionals-koleston-perfect-5-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '6/0', 'wella-professionals-koleston-perfect-6-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '7/0', 'wella-professionals-koleston-perfect-7-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '8/0', 'wella-professionals-koleston-perfect-8-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '9/0', 'wella-professionals-koleston-perfect-9-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '6/1', 'wella-professionals-koleston-perfect-6-1', 4),
  ('Wella Professionals', 'Koleston Perfect', '6/11', 'wella-professionals-koleston-perfect-6-11', 4),
  ('Wella Professionals', 'Koleston Perfect', '6/16', 'wella-professionals-koleston-perfect-6-16', 4),
  ('Wella Professionals', 'Koleston Perfect', '6/17', 'wella-professionals-koleston-perfect-6-17', 4),
  ('Wella Professionals', 'Koleston Perfect', '6/38', 'wella-professionals-koleston-perfect-6-38', 4),
  ('Wella Professionals', 'Koleston Perfect', '6/4', 'wella-professionals-koleston-perfect-6-4', 4),
  ('Wella Professionals', 'Koleston Perfect', '6/43', 'wella-professionals-koleston-perfect-6-43', 4),
  ('Wella Professionals', 'Koleston Perfect', '6/44', 'wella-professionals-koleston-perfect-6-44', 4),
  ('Wella Professionals', 'Koleston Perfect', '6/45', 'wella-professionals-koleston-perfect-6-45', 4),
  ('Wella Professionals', 'Koleston Perfect', '7/3', 'wella-professionals-koleston-perfect-7-3', 4),
  ('Wella Professionals', 'Koleston Perfect', '10/16', 'wella-professionals-koleston-perfect-10-16', 4),
  ('Wella Professionals', 'Koleston Perfect', '8/96', 'wella-professionals-koleston-perfect-8-96', 4),
  ('Wella Professionals', 'Koleston Perfect', '10/0', 'wella-professionals-koleston-perfect-10-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '33/0', 'wella-professionals-koleston-perfect-33-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '44/0', 'wella-professionals-koleston-perfect-44-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '55/0', 'wella-professionals-koleston-perfect-55-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '66/0', 'wella-professionals-koleston-perfect-66-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '77/0', 'wella-professionals-koleston-perfect-77-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '88/0', 'wella-professionals-koleston-perfect-88-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '99/0', 'wella-professionals-koleston-perfect-99-0', 4),
  ('Wella Professionals', 'Koleston Perfect', '4/07', 'wella-professionals-koleston-perfect-4-07', 4),
  ('Wella Professionals', 'Koleston Perfect', '5/07', 'wella-professionals-koleston-perfect-5-07', 4),
  ('Wella Professionals', 'Koleston Perfect', '6/07', 'wella-professionals-koleston-perfect-6-07', 4),
  ('Wella Professionals', 'Koleston Perfect', '7/07', 'wella-professionals-koleston-perfect-7-07', 4),
  ('Wella Professionals', 'Koleston Perfect', '8/07', 'wella-professionals-koleston-perfect-8-07', 4),
  ('Wella Professionals', 'Koleston Perfect', '5/18', 'wella-professionals-koleston-perfect-5-18', 4),
  ('Wella Professionals', 'Koleston Perfect', '6/91', 'wella-professionals-koleston-perfect-6-91', 4),
  ('Wella Professionals', 'Koleston Perfect', '7/1', 'wella-professionals-koleston-perfect-7-1', 4),
  ('Wella Professionals', 'Koleston Perfect', '7/17', 'wella-professionals-koleston-perfect-7-17', 4),
  ('Wella Professionals', 'Koleston Perfect', '7/18', 'wella-professionals-koleston-perfect-7-18', 4),
  ('Wella Professionals', 'Koleston Perfect', '8/1', 'wella-professionals-koleston-perfect-8-1', 4),
  ('Wella Professionals', 'Koleston Perfect', '8/97', 'wella-professionals-koleston-perfect-8-97', 4),
  ('Wella Professionals', 'Koleston Perfect', '9/1', 'wella-professionals-koleston-perfect-9-1', 4),
  ('Wella Professionals', 'Koleston Perfect', '9/16', 'wella-professionals-koleston-perfect-9-16', 4),
  ('Wella Professionals', 'Koleston Perfect', '9/17', 'wella-professionals-koleston-perfect-9-17', 4),
  ('Wella Professionals', 'Koleston Perfect', '9/38', 'wella-professionals-koleston-perfect-9-38', 4),
  ('Wella Professionals', 'Koleston Perfect', '9/81', 'wella-professionals-koleston-perfect-9-81', 4),
  ('Wella Professionals', 'Koleston Perfect', '10/1', 'wella-professionals-koleston-perfect-10-1', 4),
  ('Wella Professionals', 'Koleston Perfect', '10/3', 'wella-professionals-koleston-perfect-10-3', 4),
  ('Wella Professionals', 'Koleston Perfect', '10/31', 'wella-professionals-koleston-perfect-10-31', 4),
  ('Wella Professionals', 'Koleston Perfect', '10/96', 'wella-professionals-koleston-perfect-10-96', 4),
  ('Wella Professionals', 'Koleston Perfect', '44/44', 'wella-professionals-koleston-perfect-44-44', 4),
  ('Wella Professionals', 'Koleston Perfect', '44/65', 'wella-professionals-koleston-perfect-44-65', 4),
  ('Wella Professionals', 'Koleston Perfect', '55/46', 'wella-professionals-koleston-perfect-55-46', 4),
  ('Wella Professionals', 'Koleston Perfect', '55/65', 'wella-professionals-koleston-perfect-55-65', 4),
  ('Wella Professionals', 'Koleston Perfect', '66/44', 'wella-professionals-koleston-perfect-66-44', 4),
  ('Wella Professionals', 'Koleston Perfect', '66/46', 'wella-professionals-koleston-perfect-66-46', 4),
  ('Wella Professionals', 'Koleston Perfect', '77/44', 'wella-professionals-koleston-perfect-77-44', 4),
  ('Wella Professionals', 'Koleston Perfect', '77/46', 'wella-professionals-koleston-perfect-77-46', 4),
  ('Wella Professionals', 'Koleston Perfect', '99/44', 'wella-professionals-koleston-perfect-99-44', 4),
  ('Wella Professionals', 'Koleston Perfect', '0/11', 'wella-professionals-koleston-perfect-0-11', 4),
  ('Wella Professionals', 'Koleston Perfect', '0/28', 'wella-professionals-koleston-perfect-0-28', 4),
  ('Wella Professionals', 'Koleston Perfect', '0/33', 'wella-professionals-koleston-perfect-0-33', 4),
  ('Wella Professionals', 'Koleston Perfect', '0/44', 'wella-professionals-koleston-perfect-0-44', 4),
  ('Wella Professionals', 'Koleston Perfect', '0/66', 'wella-professionals-koleston-perfect-0-66', 4),
  ('Wella Professionals', 'Koleston Perfect', '0/88', 'wella-professionals-koleston-perfect-0-88', 4),
  ('Wella Professionals', 'Illumina Color', '6/0', 'wella-professionals-illumina-color-6-0', 4),
  ('Wella Professionals', 'Illumina Color', '7/3', 'wella-professionals-illumina-color-7-3', 4),
  ('Wella Professionals', 'Illumina Color', '10/16', 'wella-professionals-illumina-color-10-16', 4),
  ('Wella Professionals', 'Illumina Color', '5/0', 'wella-professionals-illumina-color-5-0', 4),
  ('Wella Professionals', 'Illumina Color', '9/60', 'wella-professionals-illumina-color-9-60', 4),
  ('Wella Professionals', 'Illumina Color', '5/', 'wella-professionals-illumina-color-5', 4),
  ('Wella Professionals', 'Illumina Color', '6/', 'wella-professionals-illumina-color-6', 4),
  ('Wella Professionals', 'Illumina Color', '7/', 'wella-professionals-illumina-color-7', 4),
  ('Wella Professionals', 'Illumina Color', '8/', 'wella-professionals-illumina-color-8', 4),
  ('Wella Professionals', 'Illumina Color', '9/', 'wella-professionals-illumina-color-9', 4),
  ('Wella Professionals', 'Illumina Color', '10/', 'wella-professionals-illumina-color-10', 4),
  ('Wella Professionals', 'Illumina Color', '5/7', 'wella-professionals-illumina-color-5-7', 4),
  ('Wella Professionals', 'Illumina Color', '7/7', 'wella-professionals-illumina-color-7-7', 4),
  ('Wella Professionals', 'Illumina Color', '9/7', 'wella-professionals-illumina-color-9-7', 4),
  ('Wella Professionals', 'Illumina Color', '5/81', 'wella-professionals-illumina-color-5-81', 4),
  ('Wella Professionals', 'Illumina Color', '7/81', 'wella-professionals-illumina-color-7-81', 4),
  ('Wella Professionals', 'Illumina Color', '9/81', 'wella-professionals-illumina-color-9-81', 4),
  ('Wella Professionals', 'Illumina Color', '10/81', 'wella-professionals-illumina-color-10-81', 4),
  ('Wella Professionals', 'Illumina Color', '6/16', 'wella-professionals-illumina-color-6-16', 4),
  ('Wella Professionals', 'Illumina Color', '8/16', 'wella-professionals-illumina-color-8-16', 4),
  ('Wella Professionals', 'Illumina Color', '5/35', 'wella-professionals-illumina-color-5-35', 4),
  ('Wella Professionals', 'Illumina Color', '7/35', 'wella-professionals-illumina-color-7-35', 4),
  ('Wella Professionals', 'Illumina Color', '9/03', 'wella-professionals-illumina-color-9-03', 4),
  ('Schwarzkopf', 'Igora Royal', '6-0', 'schwarzkopf-igora-royal-6-0', 4),
  ('Schwarzkopf', 'Igora Royal', '6-00', 'schwarzkopf-igora-royal-6-00', 4),
  ('Schwarzkopf', 'Igora Royal', '6-1', 'schwarzkopf-igora-royal-6-1', 4),
  ('Schwarzkopf', 'Igora Royal', '6-4', 'schwarzkopf-igora-royal-6-4', 4),
  ('Schwarzkopf', 'Igora Royal', '6-5', 'schwarzkopf-igora-royal-6-5', 4),
  ('Schwarzkopf', 'Igora Royal', '6-7', 'schwarzkopf-igora-royal-6-7', 4),
  ('Schwarzkopf', 'Igora Royal', '6-77', 'schwarzkopf-igora-royal-6-77', 4),
  ('Schwarzkopf', 'Igora Royal', '6-88', 'schwarzkopf-igora-royal-6-88', 4),
  ('Schwarzkopf', 'Igora Royal', '6-98', 'schwarzkopf-igora-royal-6-98', 4),
  ('Schwarzkopf', 'Igora Royal', '5-0', 'schwarzkopf-igora-royal-5-0', 4),
  ('Schwarzkopf', 'Igora Royal', '7-77', 'schwarzkopf-igora-royal-7-77', 4),
  ('Schwarzkopf', 'Igora Royal', '9-98', 'schwarzkopf-igora-royal-9-98', 4),
  ('Schwarzkopf', 'Igora Royal', '8-4', 'schwarzkopf-igora-royal-8-4', 4),
  ('Schwarzkopf', 'Igora Royal', '1-0', 'schwarzkopf-igora-royal-1-0', 4),
  ('Schwarzkopf', 'Igora Royal', '3-0', 'schwarzkopf-igora-royal-3-0', 4),
  ('Schwarzkopf', 'Igora Royal', '4-0', 'schwarzkopf-igora-royal-4-0', 4),
  ('Schwarzkopf', 'Igora Royal', '5-00', 'schwarzkopf-igora-royal-5-00', 4),
  ('Schwarzkopf', 'Igora Royal', '7-0', 'schwarzkopf-igora-royal-7-0', 4),
  ('Schwarzkopf', 'Igora Royal', '7-00', 'schwarzkopf-igora-royal-7-00', 4),
  ('Schwarzkopf', 'Igora Royal', '8-0', 'schwarzkopf-igora-royal-8-0', 4),
  ('Schwarzkopf', 'Igora Royal', '9-0', 'schwarzkopf-igora-royal-9-0', 4),
  ('Schwarzkopf', 'Igora Royal', '10-0', 'schwarzkopf-igora-royal-10-0', 4),
  ('Schwarzkopf', 'Igora Royal', '5-1', 'schwarzkopf-igora-royal-5-1', 4),
  ('Schwarzkopf', 'Igora Royal', '6-12', 'schwarzkopf-igora-royal-6-12', 4),
  ('Schwarzkopf', 'Igora Royal', '7-1', 'schwarzkopf-igora-royal-7-1', 4),
  ('Schwarzkopf', 'Igora Royal', '7-12', 'schwarzkopf-igora-royal-7-12', 4),
  ('Schwarzkopf', 'Igora Royal', '8-1', 'schwarzkopf-igora-royal-8-1', 4),
  ('Schwarzkopf', 'Igora Royal', '8-11', 'schwarzkopf-igora-royal-8-11', 4),
  ('Schwarzkopf', 'Igora Royal', '9-1', 'schwarzkopf-igora-royal-9-1', 4),
  ('Schwarzkopf', 'Igora Royal', '9-11', 'schwarzkopf-igora-royal-9-11', 4),
  ('Schwarzkopf', 'Igora Royal', '5-6', 'schwarzkopf-igora-royal-5-6', 4),
  ('Schwarzkopf', 'Igora Royal', '6-6', 'schwarzkopf-igora-royal-6-6', 4),
  ('Schwarzkopf', 'Igora Royal', '6-63', 'schwarzkopf-igora-royal-6-63', 4),
  ('Schwarzkopf', 'Igora Royal', '6-65', 'schwarzkopf-igora-royal-6-65', 4),
  ('Schwarzkopf', 'Igora Royal', '6-68', 'schwarzkopf-igora-royal-6-68', 4),
  ('Schwarzkopf', 'Igora Royal', '5-7', 'schwarzkopf-igora-royal-5-7', 4),
  ('Schwarzkopf', 'Igora Royal', '7-7', 'schwarzkopf-igora-royal-7-7', 4),
  ('Schwarzkopf', 'Igora Royal', '8-77', 'schwarzkopf-igora-royal-8-77', 4),
  ('Schwarzkopf', 'Igora Royal', '4-88', 'schwarzkopf-igora-royal-4-88', 4),
  ('Schwarzkopf', 'Igora Royal', '5-88', 'schwarzkopf-igora-royal-5-88', 4),
  ('Schwarzkopf', 'Igora Royal', '9.5-1', 'schwarzkopf-igora-royal-9-5-1', 4),
  ('Schwarzkopf', 'Igora Royal', '0-11', 'schwarzkopf-igora-royal-0-11', 4),
  ('Schwarzkopf', 'Igora Royal', '0-55', 'schwarzkopf-igora-royal-0-55', 4),
  ('Schwarzkopf', 'Igora Royal', '0-77', 'schwarzkopf-igora-royal-0-77', 4),
  ('Schwarzkopf', 'Igora Royal', '0-88', 'schwarzkopf-igora-royal-0-88', 4),
  ('Schwarzkopf', 'Igora Royal', '0-99', 'schwarzkopf-igora-royal-0-99', 4),
  ('Goldwell', 'Topchic', '2N', 'goldwell-topchic-2n', 4),
  ('Goldwell', 'Topchic', '3N', 'goldwell-topchic-3n', 4),
  ('Goldwell', 'Topchic', '4N', 'goldwell-topchic-4n', 4),
  ('Goldwell', 'Topchic', '5N', 'goldwell-topchic-5n', 4),
  ('Goldwell', 'Topchic', '7N', 'goldwell-topchic-7n', 4),
  ('Goldwell', 'Topchic', '8N', 'goldwell-topchic-8n', 4),
  ('Goldwell', 'Topchic', '9N', 'goldwell-topchic-9n', 4),
  ('Goldwell', 'Topchic', '10N', 'goldwell-topchic-10n', 4),
  ('Goldwell', 'Topchic', '3NN', 'goldwell-topchic-3nn', 4),
  ('Goldwell', 'Topchic', '4NN', 'goldwell-topchic-4nn', 4),
  ('Goldwell', 'Topchic', '5NN', 'goldwell-topchic-5nn', 4),
  ('Goldwell', 'Topchic', '6NN', 'goldwell-topchic-6nn', 4),
  ('Goldwell', 'Topchic', '7NN', 'goldwell-topchic-7nn', 4),
  ('Goldwell', 'Topchic', '8NN', 'goldwell-topchic-8nn', 4),
  ('Goldwell', 'Topchic', '9NN', 'goldwell-topchic-9nn', 4),
  ('Goldwell', 'Topchic', '4NA', 'goldwell-topchic-4na', 4),
  ('Goldwell', 'Topchic', '5NA', 'goldwell-topchic-5na', 4),
  ('Goldwell', 'Topchic', '6NA', 'goldwell-topchic-6na', 4),
  ('Goldwell', 'Topchic', '7NA', 'goldwell-topchic-7na', 4),
  ('Goldwell', 'Topchic', '8NA', 'goldwell-topchic-8na', 4),
  ('Goldwell', 'Topchic', '9NA', 'goldwell-topchic-9na', 4),
  ('Goldwell', 'Topchic', '7SB', 'goldwell-topchic-7sb', 4),
  ('Goldwell', 'Topchic', '8SB', 'goldwell-topchic-8sb', 4),
  ('Goldwell', 'Topchic', '9SB', 'goldwell-topchic-9sb', 4),
  ('Goldwell', 'Topchic', '6A', 'goldwell-topchic-6a', 4),
  ('Goldwell', 'Topchic', '7A', 'goldwell-topchic-7a', 4),
  ('Goldwell', 'Topchic', '8A', 'goldwell-topchic-8a', 4),
  ('Goldwell', 'Topchic', '9A', 'goldwell-topchic-9a', 4),
  ('Goldwell', 'Topchic', '5GB', 'goldwell-topchic-5gb', 4),
  ('Goldwell', 'Topchic', '6GB', 'goldwell-topchic-6gb', 4),
  ('Goldwell', 'Topchic', '7GB', 'goldwell-topchic-7gb', 4),
  ('Goldwell', 'Topchic', '8GB', 'goldwell-topchic-8gb', 4),
  ('Goldwell', 'Topchic', '9GB', 'goldwell-topchic-9gb', 4),
  ('Goldwell', 'Topchic', '6B', 'goldwell-topchic-6b', 4),
  ('Goldwell', 'Topchic', '7B', 'goldwell-topchic-7b', 4),
  ('Goldwell', 'Topchic', '8B', 'goldwell-topchic-8b', 4),
  ('Goldwell', 'Topchic', '9B', 'goldwell-topchic-9b', 4),
  ('Goldwell', 'Topchic', '7KG', 'goldwell-topchic-7kg', 4),
  ('Goldwell', 'Topchic', '8KG', 'goldwell-topchic-8kg', 4),
  ('Goldwell', 'Topchic', '9KG', 'goldwell-topchic-9kg', 4),
  ('Goldwell', 'Topchic', '6KR', 'goldwell-topchic-6kr', 4),
  ('Goldwell', 'Topchic', '7KR', 'goldwell-topchic-7kr', 4),
  ('Goldwell', 'Topchic', '5R', 'goldwell-topchic-5r', 4),
  ('Goldwell', 'Topchic', '6R', 'goldwell-topchic-6r', 4),
  ('Goldwell', 'Topchic', '7RRmax', 'goldwell-topchic-7rrmax', 4),
  ('Redken', 'Shades EQ', '01B', 'redken-shades-eq-01b', 4),
  ('Redken', 'Shades EQ', '03N', 'redken-shades-eq-03n', 4),
  ('Redken', 'Shades EQ', '03NW', 'redken-shades-eq-03nw', 4),
  ('Redken', 'Shades EQ', '04N', 'redken-shades-eq-04n', 4),
  ('Redken', 'Shades EQ', '05N', 'redken-shades-eq-05n', 4),
  ('Redken', 'Shades EQ', '06N', 'redken-shades-eq-06n', 4),
  ('Redken', 'Shades EQ', '06NB', 'redken-shades-eq-06nb', 4),
  ('Redken', 'Shades EQ', '06GB', 'redken-shades-eq-06gb', 4),
  ('Redken', 'Shades EQ', '06GG', 'redken-shades-eq-06gg', 4),
  ('Redken', 'Shades EQ', '07N', 'redken-shades-eq-07n', 4),
  ('Redken', 'Shades EQ', '07NB', 'redken-shades-eq-07nb', 4),
  ('Redken', 'Shades EQ', '07G', 'redken-shades-eq-07g', 4),
  ('Redken', 'Shades EQ', '07GR', 'redken-shades-eq-07gr', 4),
  ('Redken', 'Shades EQ', '08N', 'redken-shades-eq-08n', 4),
  ('Redken', 'Shades EQ', '08GG', 'redken-shades-eq-08gg', 4),
  ('Redken', 'Shades EQ', '09N', 'redken-shades-eq-09n', 4),
  ('Redken', 'Shades EQ', '09NB', 'redken-shades-eq-09nb', 4),
  ('Redken', 'Shades EQ', '09G', 'redken-shades-eq-09g', 4),
  ('Redken', 'Shades EQ', '09GB', 'redken-shades-eq-09gb', 4),
  ('Redken', 'Shades EQ', '09T', 'redken-shades-eq-09t', 4),
  ('Redken', 'Shades EQ', '09AA', 'redken-shades-eq-09aa', 4),
  ('Redken', 'Shades EQ', '010N', 'redken-shades-eq-010n', 4),
  ('Redken', 'Shades EQ', '010VV', 'redken-shades-eq-010vv', 4),
  ('Aveda', 'Full Spectrum', '1N', 'aveda-full-spectrum-1n', 4),
  ('Aveda', 'Full Spectrum', '2N', 'aveda-full-spectrum-2n', 4),
  ('Aveda', 'Full Spectrum', '3N', 'aveda-full-spectrum-3n', 4),
  ('Aveda', 'Full Spectrum', '4N', 'aveda-full-spectrum-4n', 4),
  ('Aveda', 'Full Spectrum', '5N', 'aveda-full-spectrum-5n', 4),
  ('Aveda', 'Full Spectrum', '6N', 'aveda-full-spectrum-6n', 4),
  ('Aveda', 'Full Spectrum', '7N', 'aveda-full-spectrum-7n', 4),
  ('Aveda', 'Full Spectrum', '8N', 'aveda-full-spectrum-8n', 4),
  ('Aveda', 'Full Spectrum', '9N', 'aveda-full-spectrum-9n', 4),
  ('Aveda', 'Full Spectrum', '10N', 'aveda-full-spectrum-10n', 4),
  ('yuv', 'Custom System', '1', 'yuv-custom-system-1', 4),
  ('yuv', 'Custom System', '2', 'yuv-custom-system-2', 4),
  ('yuv', 'Custom System', '3', 'yuv-custom-system-3', 4),
  ('yuv', 'Custom System', '4', 'yuv-custom-system-4', 4),
  ('yuv', 'Custom System', '5', 'yuv-custom-system-5', 4),
  ('yuv', 'Custom System', '6', 'yuv-custom-system-6', 4),
  ('yuv', 'Custom System', '7', 'yuv-custom-system-7', 4),
  ('yuv', 'Custom System', '8', 'yuv-custom-system-8', 4),
  ('yuv', 'Custom System', '9', 'yuv-custom-system-9', 4),
  ('yuv', 'Custom System', '10', 'yuv-custom-system-10', 4)
on conflict (sku) do nothing;

-- Seed initial stock balances for the 10 stocked products only.
-- ON CONFLICT DO NOTHING is intentional: re-running this seed must never
-- overwrite live scanned inventory balances, it only creates the row once.
insert into inventory (product_id, full_quantity, partial_quantity)
select p.id, v.full_quantity, 0
from (values
  ('redken-shades-eq-09v', 9),
  ('l-or-al-professionnel-majirel-6-3', 4),
  ('wella-professionals-koleston-perfect-7-43', 10),
  ('schwarzkopf-igora-royal-5-65', 2),
  ('goldwell-topchic-6n', 5),
  ('redken-shades-eq-7na', 1),
  ('wella-professionals-illumina-color-8-69', 7),
  ('l-or-al-professionnel-inoa-7-1', 2),
  ('schwarzkopf-igora-royal-4-99', 3),
  ('goldwell-elumen-bl-all', 6)
) as v(sku, full_quantity)
join products p on p.sku = v.sku
on conflict (product_id) do nothing;

-- Seeded 10 stocked products and 289 catalog reference products.
